/**
 * 头部导航数据
 * @author xq(qi.xu@yoho.cn)
 * @date: 2015/7/31
 */
module.exports = {
    gobytype: 'gobuygirls',
    searchcate: 'searchcategirls',
    navbars: [{
        name_cn: '创意生活',
        name_en: 'LIFESTYLE',
        classname: 'boys', 
        link: '',
        index_main: 4,
        subnav: [{
            name: '新品到着',
            link: '',
            index_sub: 0,
            thirdnav: [{
                title: '上装',
                branditems: [{
                    brandname: '背心',
                    link: ''
                }, {
                    brandname: 'T恤',
                    link: ''
                }, {
                    brandname: '衬衫',
                    link: ''
                }, {
                    brandname: 'POLO',
                    link: ''
                }, {
                    brandname: '毛衣/针织',
                    link: ''
                }]
            }, {
                title: '下装',
                branditems: [{
                    brandname: '短裤',
                    link: ''
                }, {
                    brandname: '休闲裤',
                    link: ''
                }, {
                    brandname: '牛仔裤',
                    link: ''
                }, {
                    brandname: '打底裤',
                    link: ''
                }]
            }, {
                title: '经典款型',
                branditems: [{
                    brandname: '夏威夷衬衫',
                    link: ''
                }, {
                    brandname: '英伦风衬衫',
                    link: ''
                }, {
                    brandname: '直筒裤',
                    link: ''
                }, {
                    brandname: '工装裤',
                    link: ''
                }, {
                    brandname: '背心',
                    link: ''
                }, {
                    brandname: '内衣',
                    link: ''
                }, {
                    brandname: '短裤',
                    link: ''
                }, {
                    brandname: '哈伦裤',
                    link: ''
                }]
            }, {
                title: '设计风',
                branditems: [{
                    brandname: '韩范儿',
                    link: ''
                }, {
                    brandname: '赫本',
                    link: ''
                }, {
                    brandname: '蕾丝',
                    link: ''
                }, {
                    brandname: '欧根纱',
                    link: ''
                }, {
                    brandname: '条纶',
                    link: ''
                }, {
                    brandname: '毛尼',
                    link: ''
                }]
            }]
        }, {
            name: '逛',
            link: '',
            thirdnav: [{
                title: '上装2',
                branditems: [{
                    brandname: '背心2',
                    link: ''
                }, {
                    brandname: 'T恤2',
                    link: ''
                }, {
                    brandname: '衬衫2',
                    link: ''
                }, {
                    brandname: 'POLO2',
                    link: ''
                }, {
                    brandname: '毛衣/针织2',
                    link: ''
                }]
            }, {
                title: '下装2',
                branditems: [{
                    brandname: '短裤2',
                    link: ''
                }, {
                    brandname: '休闲裤2',
                    link: ''
                }, {
                    brandname: '牛仔裤2',
                    link: ''
                }, {
                    brandname: '打底裤2',
                    link: ''
                }]
            }, {
                title: '经典款型2',
                branditems: [{
                    brandname: '夏威夷衬衫2',
                    link: ''
                }, {
                    brandname: '英伦风衬衫2',
                    link: ''
                }, {
                    brandname: '直筒裤2',
                    link: ''
                }, {
                    brandname: '工装裤2',
                    link: ''
                }, {
                    brandname: '背心2',
                    link: ''
                }, {
                    brandname: '内衣2',
                    link: ''
                }, {
                    brandname: '短裤2',
                    link: ''
                }, {
                    brandname: '哈伦裤',
                    link: ''
                }]
            }, {
                title: '设计风3',
                branditems: [{
                    brandname: '韩范儿3',
                    link: ''
                }, {
                    brandname: '赫本3',
                    link: ''
                }, {
                    brandname: '蕾丝3',
                    link: ''
                }, {
                    brandname: '欧根纱3',
                    link: ''
                }, {
                    brandname: '条纶',
                    link: ''
                }, {
                    brandname: '毛尼',
                    link: ''
                }]
            }]
        }, {
            name: '潮流资讯',
            link: '',
            thirdnav: [{
                title: '上装3',
                branditems: [{
                    brandname: '背心3',
                    link: ''
                }, {
                    brandname: 'T恤3',
                    link: ''
                }, {
                    brandname: '衬衫',
                    link: ''
                }, {
                    brandname: 'POLO',
                    link: ''
                }, {
                    brandname: '毛衣/针织',
                    link: ''
                }]
            }, {
                title: '下装',
                branditems: [{
                    brandname: '短裤',
                    link: ''
                }, {
                    brandname: '休闲裤',
                    link: ''
                }, {
                    brandname: '牛仔裤',
                    link: ''
                }, {
                    brandname: '打底裤',
                    link: ''
                }]
            }, {
                title: '经典款型',
                branditems: [{
                    brandname: '夏威夷衬衫',
                    link: ''
                }, {
                    brandname: '英伦风衬衫',
                    link: ''
                }, {
                    brandname: '直筒裤',
                    link: ''
                }, {
                    brandname: '工装裤',
                    link: ''
                }, {
                    brandname: '背心',
                    link: ''
                }, {
                    brandname: '内衣',
                    link: ''
                }, {
                    brandname: '短裤',
                    link: ''
                }, {
                    brandname: '哈伦裤',
                    link: ''
                }]
            }, {
                title: '设计风',
                branditems: [{
                    brandname: '韩范儿',
                    link: ''
                }, {
                    brandname: '赫本',
                    link: ''
                }, {
                    brandname: '蕾丝',
                    link: ''
                }, {
                    brandname: '欧根纱',
                    link: ''
                }, {
                    brandname: '条纶',
                    link: ''
                }, {
                    brandname: '毛尼',
                    link: ''
                }]
            }]
        }, {
            name: 'SALE',
            link: '',
            thirdnav: [{
                title: '上装',
                branditems: [{
                    brandname: '背心',
                    link: ''
                }, {
                    brandname: 'T恤',
                    link: ''
                }, {
                    brandname: '衬衫',
                    link: ''
                }, {
                    brandname: 'POLO',
                    link: ''
                }, {
                    brandname: '毛衣/针织',
                    link: ''
                }]
            }, {
                title: '下装',
                branditems: [{
                    brandname: '短裤',
                    link: ''
                }, {
                    brandname: '休闲裤',
                    link: ''
                }, {
                    brandname: '牛仔裤',
                    link: ''
                }, {
                    brandname: '打底裤',
                    link: ''
                }]
            }, {
                title: '经典款型',
                branditems: [{
                    brandname: '夏威夷衬衫',
                    link: ''
                }, {
                    brandname: '英伦风衬衫',
                    link: ''
                }, {
                    brandname: '直筒裤',
                    link: ''
                }, {
                    brandname: '工装裤',
                    link: ''
                }, {
                    brandname: '背心',
                    link: ''
                }, {
                    brandname: '内衣',
                    link: ''
                }, {
                    brandname: '短裤',
                    link: ''
                }, {
                    brandname: '哈伦裤',
                    link: ''
                }]
            }, {
                title: '设计风',
                branditems: [{
                    brandname: '韩范儿',
                    link: ''
                }, {
                    brandname: '赫本',
                    link: ''
                }, {
                    brandname: '蕾丝',
                    link: ''
                }, {
                    brandname: '欧根纱',
                    link: ''
                }, {
                    brandname: '条纶',
                    link: ''
                }, {
                    brandname: '毛尼',
                    link: ''
                }]
            }]
        }]
    }],
    myyoho: {
        email: 'caomei@163.com',
        viptype: '普通会员',
        currentscore: 495,
        totalscore: 600,
        cardtype: '银卡',
        infolist: [{
            name: '待处理的订单',
            link: '',
            num: '0'
        }, {
            name: '我的收藏',
            link: '',
            num: '1'
        }, {
            name: '我的优惠券',
            link: '',
            num: '2'
        }, {
            name: '我的YOHO币',
            link: '',
            num: '1'
        }, {
            name: '我的退货换货',
            link: '',
            num: '1'
        }],
        updlink: ''
    },
    gobuy: {
        gobuynum: 3
    },
    breadcrumbnav: [{
        notend: {
            link: 'http://www.yohobuy.com',
            name: 'BOYS首页'
        }
    }, {
        notend: {
            link: 'http://www.yohobuy.com',
            name: '上衣'
        }
    }, {
        isend: {
            link: 'http://list.yohobuy.com/?msort=1&amp;gender=1,3',
            name: '衬衫'
        }
    }]
};